import image1 from "../../assest/img/product01.jpeg";
import image2 from "../../assest/img/product02.jpeg";
import image3 from "../../assest/img/product03.jpeg";
import image4 from "../../assest/img/product04.jpeg";
import image5 from "../../assest/img/product05.jpeg";
import image6 from "../../assest/img/product06.jpeg";
export const Data = [
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		_id: 1,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 2,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 3,
		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 4,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 5,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
	{
		id: 6,

		category: "mobile-apps",
		productName: "orange Tomato",
		productImage: image1,
		price: 1200,
		sellingPrice: 12,
		description: "this is available",
	},
];
